import type { Metadata } from "next";
import "./globals.css";
import { Noto_Kufi_Arabic } from "next/font/google";

const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-kufi-arabic",
  fallback: ["Noto Kufi Arabic Fallback", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${notoKufiArabic.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
